version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: containers/php/Dockerfile
    volumes:
      - ./src:/var/www/
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: subscription_service
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    ports:
    - 3309:3306

volumes:
  data: